### PR TITLE
bin2sgl C version (non Windows OSes).

### PR DESCRIPTION
**Pull request by f1rmb**
Hi,
   this is the C port of the C# bin2sgl tool.
That way, It's possible to build the firmware under Linux (and probably OSX). I personnaly used the MCUXpresso v11.0.1_2563 and SDK v2.6.0 flawlessly.

Bear in mind that it's untested, my GD-77 is on its way (I should received it on Friday).

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I will review and merge.

I have versions C compilers on both my Windows and Linux machines

**Comment by f1rmb** [comment]
Thanks Roger,

   I've pushed another small change, moving the C file to the bin2sgl subdir, otherwise compilation will fail since it collide with existing bin2sgl subdir itself.

**Comment by rogerclarkmelbourne** [comment]
OK.

I am quite busy with the OpenGD77 today as there are some PRs to process, and I am also adding power level display etc.

But I will review and merge this at the weekend

**Comment by f1rmb** [comment]
No problem Roger.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
@f1rmb 

BTW. Can you email me, as sometimes its good to discuss things offline

**Pull request closed without merging**
