### PR TITLE
Updated the HR_C6000 translation. Now on ver. 0.2

### PR DESCRIPTION
**Pull request by acontini**
Hello, I'm continuously improving the translation of the HR_C6000 datasheet.

Andrea

### CODE REVIEW

**Comment by acontini** [comment]
I've also added some extra docs.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I already have one pdf for the MK22, which may contain the same information as in the pdf in this PR, but I'll merge the PR and I can remove duplicates later

**Comment by rogerclarkmelbourne** [comment]
Thanks again...

I just looked at the MK22 pdf you included and its not the electronic / physical reference, not the programming reference, so is not a duplicate

**Comment by acontini** [comment]
Happy to help.

**Pull request merged**
